//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("IThemeSkyModel", "FK_THEMECOM_REFERENCE_THEME", "Theme", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IThemeSky.UI.Models.Theme), "ThemeComment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IThemeSky.UI.Models.ThemeComment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("IThemeSkyModel", "FK_THEMEDOW_REFERENCE_THEME", "Theme", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IThemeSky.UI.Models.Theme), "ThemeDownloadHistory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IThemeSky.UI.Models.ThemeDownloadHistory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("IThemeSkyModel", "FK_THEMEFIL_REFERENCE_THEME", "Theme", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IThemeSky.UI.Models.Theme), "ThemeFiles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IThemeSky.UI.Models.ThemeFiles))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("IThemeSkyModel", "FK_THEMETAG_REFERENCE_THEME", "Theme", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IThemeSky.UI.Models.Theme), "ThemeTagMap", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IThemeSky.UI.Models.ThemeTagMap))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("IThemeSkyModel", "FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IThemeSky.UI.Models.ThemeTag), "ThemeTagMap", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IThemeSky.UI.Models.ThemeTagMap))]

// Original file name:
// Generation date: 2010-3-9 11:21:12
namespace IThemeSky.UI.Models
{
    
    /// <summary>
    /// There are no comments for IThemeSkyEntities in the schema.
    /// </summary>
    public partial class IThemeSkyEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new IThemeSkyEntities object using the connection string found in the 'IThemeSkyEntities' section of the application configuration file.
        /// </summary>
        public IThemeSkyEntities() : 
                base("name=IThemeSkyEntities", "IThemeSkyEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new IThemeSkyEntities object.
        /// </summary>
        public IThemeSkyEntities(string connectionString) : 
                base(connectionString, "IThemeSkyEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new IThemeSkyEntities object.
        /// </summary>
        public IThemeSkyEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "IThemeSkyEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Theme> Theme
        {
            get
            {
                if ((this._Theme == null))
                {
                    this._Theme = base.CreateQuery<Theme>("[Theme]");
                }
                return this._Theme;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Theme> _Theme;
        /// <summary>
        /// There are no comments for ThemeCategory in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ThemeCategory> ThemeCategory
        {
            get
            {
                if ((this._ThemeCategory == null))
                {
                    this._ThemeCategory = base.CreateQuery<ThemeCategory>("[ThemeCategory]");
                }
                return this._ThemeCategory;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ThemeCategory> _ThemeCategory;
        /// <summary>
        /// There are no comments for ThemeComment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ThemeComment> ThemeComment
        {
            get
            {
                if ((this._ThemeComment == null))
                {
                    this._ThemeComment = base.CreateQuery<ThemeComment>("[ThemeComment]");
                }
                return this._ThemeComment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ThemeComment> _ThemeComment;
        /// <summary>
        /// There are no comments for ThemeDownloadHistory in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ThemeDownloadHistory> ThemeDownloadHistory
        {
            get
            {
                if ((this._ThemeDownloadHistory == null))
                {
                    this._ThemeDownloadHistory = base.CreateQuery<ThemeDownloadHistory>("[ThemeDownloadHistory]");
                }
                return this._ThemeDownloadHistory;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ThemeDownloadHistory> _ThemeDownloadHistory;
        /// <summary>
        /// There are no comments for ThemeFiles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ThemeFiles> ThemeFiles
        {
            get
            {
                if ((this._ThemeFiles == null))
                {
                    this._ThemeFiles = base.CreateQuery<ThemeFiles>("[ThemeFiles]");
                }
                return this._ThemeFiles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ThemeFiles> _ThemeFiles;
        /// <summary>
        /// There are no comments for ThemeTag in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ThemeTag> ThemeTag
        {
            get
            {
                if ((this._ThemeTag == null))
                {
                    this._ThemeTag = base.CreateQuery<ThemeTag>("[ThemeTag]");
                }
                return this._ThemeTag;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ThemeTag> _ThemeTag;
        /// <summary>
        /// There are no comments for ThemeTagMap in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ThemeTagMap> ThemeTagMap
        {
            get
            {
                if ((this._ThemeTagMap == null))
                {
                    this._ThemeTagMap = base.CreateQuery<ThemeTagMap>("[ThemeTagMap]");
                }
                return this._ThemeTagMap;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ThemeTagMap> _ThemeTagMap;
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        public void AddToTheme(Theme theme)
        {
            base.AddObject("Theme", theme);
        }
        /// <summary>
        /// There are no comments for ThemeCategory in the schema.
        /// </summary>
        public void AddToThemeCategory(ThemeCategory themeCategory)
        {
            base.AddObject("ThemeCategory", themeCategory);
        }
        /// <summary>
        /// There are no comments for ThemeComment in the schema.
        /// </summary>
        public void AddToThemeComment(ThemeComment themeComment)
        {
            base.AddObject("ThemeComment", themeComment);
        }
        /// <summary>
        /// There are no comments for ThemeDownloadHistory in the schema.
        /// </summary>
        public void AddToThemeDownloadHistory(ThemeDownloadHistory themeDownloadHistory)
        {
            base.AddObject("ThemeDownloadHistory", themeDownloadHistory);
        }
        /// <summary>
        /// There are no comments for ThemeFiles in the schema.
        /// </summary>
        public void AddToThemeFiles(ThemeFiles themeFiles)
        {
            base.AddObject("ThemeFiles", themeFiles);
        }
        /// <summary>
        /// There are no comments for ThemeTag in the schema.
        /// </summary>
        public void AddToThemeTag(ThemeTag themeTag)
        {
            base.AddObject("ThemeTag", themeTag);
        }
        /// <summary>
        /// There are no comments for ThemeTagMap in the schema.
        /// </summary>
        public void AddToThemeTagMap(ThemeTagMap themeTagMap)
        {
            base.AddObject("ThemeTagMap", themeTagMap);
        }
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.Theme in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ThemeId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="Theme")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Theme : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Theme object.
        /// </summary>
        /// <param name="themeId">Initial value of ThemeId.</param>
        public static Theme CreateTheme(int themeId)
        {
            Theme theme = new Theme();
            theme.ThemeId = themeId;
            return theme;
        }
        /// <summary>
        /// There are no comments for Property ThemeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ThemeId
        {
            get
            {
                return this._ThemeId;
            }
            set
            {
                this.OnThemeIdChanging(value);
                this.ReportPropertyChanging("ThemeId");
                this._ThemeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ThemeId");
                this.OnThemeIdChanged();
            }
        }
        private int _ThemeId;
        partial void OnThemeIdChanging(int value);
        partial void OnThemeIdChanged();
        /// <summary>
        /// There are no comments for Property CategoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CategoryId
        {
            get
            {
                return this._CategoryId;
            }
            set
            {
                this.OnCategoryIdChanging(value);
                this.ReportPropertyChanging("CategoryId");
                this._CategoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryId");
                this.OnCategoryIdChanged();
            }
        }
        private global::System.Nullable<int> _CategoryId;
        partial void OnCategoryIdChanging(global::System.Nullable<int> value);
        partial void OnCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property ParentCategoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentCategoryId
        {
            get
            {
                return this._ParentCategoryId;
            }
            set
            {
                this.OnParentCategoryIdChanging(value);
                this.ReportPropertyChanging("ParentCategoryId");
                this._ParentCategoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentCategoryId");
                this.OnParentCategoryIdChanged();
            }
        }
        private global::System.Nullable<int> _ParentCategoryId;
        partial void OnParentCategoryIdChanging(global::System.Nullable<int> value);
        partial void OnParentCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property FileSize in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> FileSize
        {
            get
            {
                return this._FileSize;
            }
            set
            {
                this.OnFileSizeChanging(value);
                this.ReportPropertyChanging("FileSize");
                this._FileSize = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FileSize");
                this.OnFileSizeChanged();
            }
        }
        private global::System.Nullable<long> _FileSize;
        partial void OnFileSizeChanging(global::System.Nullable<long> value);
        partial void OnFileSizeChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property DisplayState in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> DisplayState
        {
            get
            {
                return this._DisplayState;
            }
            set
            {
                this.OnDisplayStateChanging(value);
                this.ReportPropertyChanging("DisplayState");
                this._DisplayState = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DisplayState");
                this.OnDisplayStateChanged();
            }
        }
        private global::System.Nullable<short> _DisplayState;
        partial void OnDisplayStateChanging(global::System.Nullable<short> value);
        partial void OnDisplayStateChanged();
        /// <summary>
        /// There are no comments for Property CheckState in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> CheckState
        {
            get
            {
                return this._CheckState;
            }
            set
            {
                this.OnCheckStateChanging(value);
                this.ReportPropertyChanging("CheckState");
                this._CheckState = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CheckState");
                this.OnCheckStateChanged();
            }
        }
        private global::System.Nullable<short> _CheckState;
        partial void OnCheckStateChanging(global::System.Nullable<short> value);
        partial void OnCheckStateChanged();
        /// <summary>
        /// There are no comments for Property AuthorId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> AuthorId
        {
            get
            {
                return this._AuthorId;
            }
            set
            {
                this.OnAuthorIdChanging(value);
                this.ReportPropertyChanging("AuthorId");
                this._AuthorId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AuthorId");
                this.OnAuthorIdChanged();
            }
        }
        private global::System.Nullable<int> _AuthorId;
        partial void OnAuthorIdChanging(global::System.Nullable<int> value);
        partial void OnAuthorIdChanged();
        /// <summary>
        /// There are no comments for Property CheckerId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CheckerId
        {
            get
            {
                return this._CheckerId;
            }
            set
            {
                this.OnCheckerIdChanging(value);
                this.ReportPropertyChanging("CheckerId");
                this._CheckerId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CheckerId");
                this.OnCheckerIdChanged();
            }
        }
        private global::System.Nullable<int> _CheckerId;
        partial void OnCheckerIdChanging(global::System.Nullable<int> value);
        partial void OnCheckerIdChanged();
        /// <summary>
        /// There are no comments for Property CommendIndex in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CommendIndex
        {
            get
            {
                return this._CommendIndex;
            }
            set
            {
                this.OnCommendIndexChanging(value);
                this.ReportPropertyChanging("CommendIndex");
                this._CommendIndex = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CommendIndex");
                this.OnCommendIndexChanged();
            }
        }
        private global::System.Nullable<int> _CommendIndex;
        partial void OnCommendIndexChanging(global::System.Nullable<int> value);
        partial void OnCommendIndexChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailName
        {
            get
            {
                return this._ThumbnailName;
            }
            set
            {
                this.OnThumbnailNameChanging(value);
                this.ReportPropertyChanging("ThumbnailName");
                this._ThumbnailName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ThumbnailName");
                this.OnThumbnailNameChanged();
            }
        }
        private string _ThumbnailName;
        partial void OnThumbnailNameChanging(string value);
        partial void OnThumbnailNameChanged();
        /// <summary>
        /// There are no comments for Property AddTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> AddTime
        {
            get
            {
                return this._AddTime;
            }
            set
            {
                this.OnAddTimeChanging(value);
                this.ReportPropertyChanging("AddTime");
                this._AddTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddTime");
                this.OnAddTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _AddTime;
        partial void OnAddTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddTimeChanged();
        /// <summary>
        /// There are no comments for Property UpdateTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return this._UpdateTime;
            }
            set
            {
                this.OnUpdateTimeChanging(value);
                this.ReportPropertyChanging("UpdateTime");
                this._UpdateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpdateTime");
                this.OnUpdateTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();
        /// <summary>
        /// There are no comments for Property GoodComments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> GoodComments
        {
            get
            {
                return this._GoodComments;
            }
            set
            {
                this.OnGoodCommentsChanging(value);
                this.ReportPropertyChanging("GoodComments");
                this._GoodComments = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GoodComments");
                this.OnGoodCommentsChanged();
            }
        }
        private global::System.Nullable<int> _GoodComments;
        partial void OnGoodCommentsChanging(global::System.Nullable<int> value);
        partial void OnGoodCommentsChanged();
        /// <summary>
        /// There are no comments for Property BadComments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> BadComments
        {
            get
            {
                return this._BadComments;
            }
            set
            {
                this.OnBadCommentsChanging(value);
                this.ReportPropertyChanging("BadComments");
                this._BadComments = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BadComments");
                this.OnBadCommentsChanged();
            }
        }
        private global::System.Nullable<int> _BadComments;
        partial void OnBadCommentsChanging(global::System.Nullable<int> value);
        partial void OnBadCommentsChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this.ReportPropertyChanging("Comments");
                this._Comments = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Comments");
                this.OnCommentsChanged();
            }
        }
        private global::System.Nullable<int> _Comments;
        partial void OnCommentsChanging(global::System.Nullable<int> value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property Downloads in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Downloads
        {
            get
            {
                return this._Downloads;
            }
            set
            {
                this.OnDownloadsChanging(value);
                this.ReportPropertyChanging("Downloads");
                this._Downloads = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Downloads");
                this.OnDownloadsChanged();
            }
        }
        private global::System.Nullable<int> _Downloads;
        partial void OnDownloadsChanging(global::System.Nullable<int> value);
        partial void OnDownloadsChanged();
        /// <summary>
        /// There are no comments for Property Views in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Views
        {
            get
            {
                return this._Views;
            }
            set
            {
                this.OnViewsChanging(value);
                this.ReportPropertyChanging("Views");
                this._Views = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Views");
                this.OnViewsChanged();
            }
        }
        private global::System.Nullable<int> _Views;
        partial void OnViewsChanging(global::System.Nullable<int> value);
        partial void OnViewsChanged();
        /// <summary>
        /// There are no comments for Property LastWeekDownloads in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LastWeekDownloads
        {
            get
            {
                return this._LastWeekDownloads;
            }
            set
            {
                this.OnLastWeekDownloadsChanging(value);
                this.ReportPropertyChanging("LastWeekDownloads");
                this._LastWeekDownloads = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastWeekDownloads");
                this.OnLastWeekDownloadsChanged();
            }
        }
        private global::System.Nullable<int> _LastWeekDownloads;
        partial void OnLastWeekDownloadsChanging(global::System.Nullable<int> value);
        partial void OnLastWeekDownloadsChanged();
        /// <summary>
        /// There are no comments for Property LastMonthDownloads in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LastMonthDownloads
        {
            get
            {
                return this._LastMonthDownloads;
            }
            set
            {
                this.OnLastMonthDownloadsChanging(value);
                this.ReportPropertyChanging("LastMonthDownloads");
                this._LastMonthDownloads = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastMonthDownloads");
                this.OnLastMonthDownloadsChanged();
            }
        }
        private global::System.Nullable<int> _LastMonthDownloads;
        partial void OnLastMonthDownloadsChanging(global::System.Nullable<int> value);
        partial void OnLastMonthDownloadsChanged();
        /// <summary>
        /// There are no comments for Property Source in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this.OnSourceChanging(value);
                this.ReportPropertyChanging("Source");
                this._Source = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Source");
                this.OnSourceChanged();
            }
        }
        private global::System.Nullable<int> _Source;
        partial void OnSourceChanging(global::System.Nullable<int> value);
        partial void OnSourceChanged();
        /// <summary>
        /// There are no comments for ThemeComment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMECOM_REFERENCE_THEME", "ThemeComment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ThemeComment> ThemeComment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ThemeComment>("IThemeSkyModel.FK_THEMECOM_REFERENCE_THEME", "ThemeComment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ThemeComment>("IThemeSkyModel.FK_THEMECOM_REFERENCE_THEME", "ThemeComment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ThemeDownloadHistory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMEDOW_REFERENCE_THEME", "ThemeDownloadHistory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ThemeDownloadHistory> ThemeDownloadHistory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ThemeDownloadHistory>("IThemeSkyModel.FK_THEMEDOW_REFERENCE_THEME", "ThemeDownloadHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ThemeDownloadHistory>("IThemeSkyModel.FK_THEMEDOW_REFERENCE_THEME", "ThemeDownloadHistory", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ThemeFiles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMEFIL_REFERENCE_THEME", "ThemeFiles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ThemeFiles> ThemeFiles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ThemeFiles>("IThemeSkyModel.FK_THEMEFIL_REFERENCE_THEME", "ThemeFiles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ThemeFiles>("IThemeSkyModel.FK_THEMEFIL_REFERENCE_THEME", "ThemeFiles", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ThemeTagMap in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMETAG_REFERENCE_THEME", "ThemeTagMap")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ThemeTagMap> ThemeTagMap
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ThemeTagMap>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEME", "ThemeTagMap");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ThemeTagMap>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEME", "ThemeTagMap", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.ThemeCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="ThemeCategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThemeCategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThemeCategory object.
        /// </summary>
        /// <param name="categoryId">Initial value of CategoryId.</param>
        public static ThemeCategory CreateThemeCategory(int categoryId)
        {
            ThemeCategory themeCategory = new ThemeCategory();
            themeCategory.CategoryId = categoryId;
            return themeCategory;
        }
        /// <summary>
        /// There are no comments for Property CategoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this._CategoryId;
            }
            set
            {
                this.OnCategoryIdChanging(value);
                this.ReportPropertyChanging("CategoryId");
                this._CategoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryId");
                this.OnCategoryIdChanged();
            }
        }
        private int _CategoryId;
        partial void OnCategoryIdChanging(int value);
        partial void OnCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property CategoryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                this.ReportPropertyChanging("CategoryName");
                this._CategoryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CategoryName");
                this.OnCategoryNameChanged();
            }
        }
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property ParentId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentId
        {
            get
            {
                return this._ParentId;
            }
            set
            {
                this.OnParentIdChanging(value);
                this.ReportPropertyChanging("ParentId");
                this._ParentId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentId");
                this.OnParentIdChanged();
            }
        }
        private global::System.Nullable<int> _ParentId;
        partial void OnParentIdChanging(global::System.Nullable<int> value);
        partial void OnParentIdChanged();
        /// <summary>
        /// There are no comments for Property CategoryIcon in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryIcon
        {
            get
            {
                return this._CategoryIcon;
            }
            set
            {
                this.OnCategoryIconChanging(value);
                this.ReportPropertyChanging("CategoryIcon");
                this._CategoryIcon = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CategoryIcon");
                this.OnCategoryIconChanged();
            }
        }
        private string _CategoryIcon;
        partial void OnCategoryIconChanging(string value);
        partial void OnCategoryIconChanged();
        /// <summary>
        /// There are no comments for Property SortNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortNumber
        {
            get
            {
                return this._SortNumber;
            }
            set
            {
                this.OnSortNumberChanging(value);
                this.ReportPropertyChanging("SortNumber");
                this._SortNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortNumber");
                this.OnSortNumberChanged();
            }
        }
        private global::System.Nullable<int> _SortNumber;
        partial void OnSortNumberChanging(global::System.Nullable<int> value);
        partial void OnSortNumberChanged();
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.ThemeComment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CommentId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="ThemeComment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThemeComment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThemeComment object.
        /// </summary>
        /// <param name="commentId">Initial value of CommentId.</param>
        public static ThemeComment CreateThemeComment(long commentId)
        {
            ThemeComment themeComment = new ThemeComment();
            themeComment.CommentId = commentId;
            return themeComment;
        }
        /// <summary>
        /// There are no comments for Property CommentId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long CommentId
        {
            get
            {
                return this._CommentId;
            }
            set
            {
                this.OnCommentIdChanging(value);
                this.ReportPropertyChanging("CommentId");
                this._CommentId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CommentId");
                this.OnCommentIdChanged();
            }
        }
        private long _CommentId;
        partial void OnCommentIdChanging(long value);
        partial void OnCommentIdChanged();
        /// <summary>
        /// There are no comments for Property RateType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> RateType
        {
            get
            {
                return this._RateType;
            }
            set
            {
                this.OnRateTypeChanging(value);
                this.ReportPropertyChanging("RateType");
                this._RateType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RateType");
                this.OnRateTypeChanged();
            }
        }
        private global::System.Nullable<int> _RateType;
        partial void OnRateTypeChanging(global::System.Nullable<int> value);
        partial void OnRateTypeChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private global::System.Nullable<int> _UserId;
        partial void OnUserIdChanging(global::System.Nullable<int> value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property UserIp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIp
        {
            get
            {
                return this._UserIp;
            }
            set
            {
                this.OnUserIpChanging(value);
                this.ReportPropertyChanging("UserIp");
                this._UserIp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserIp");
                this.OnUserIpChanged();
            }
        }
        private string _UserIp;
        partial void OnUserIpChanging(string value);
        partial void OnUserIpChanged();
        /// <summary>
        /// There are no comments for Property AddTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> AddTime
        {
            get
            {
                return this._AddTime;
            }
            set
            {
                this.OnAddTimeChanging(value);
                this.ReportPropertyChanging("AddTime");
                this._AddTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddTime");
                this.OnAddTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _AddTime;
        partial void OnAddTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddTimeChanged();
        /// <summary>
        /// There are no comments for Property UpdateTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return this._UpdateTime;
            }
            set
            {
                this.OnUpdateTimeChanging(value);
                this.ReportPropertyChanging("UpdateTime");
                this._UpdateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpdateTime");
                this.OnUpdateTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();
        /// <summary>
        /// There are no comments for Property DiggNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> DiggNumber
        {
            get
            {
                return this._DiggNumber;
            }
            set
            {
                this.OnDiggNumberChanging(value);
                this.ReportPropertyChanging("DiggNumber");
                this._DiggNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DiggNumber");
                this.OnDiggNumberChanged();
            }
        }
        private global::System.Nullable<int> _DiggNumber;
        partial void OnDiggNumberChanging(global::System.Nullable<int> value);
        partial void OnDiggNumberChanged();
        /// <summary>
        /// There are no comments for Property BuryNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> BuryNumber
        {
            get
            {
                return this._BuryNumber;
            }
            set
            {
                this.OnBuryNumberChanging(value);
                this.ReportPropertyChanging("BuryNumber");
                this._BuryNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BuryNumber");
                this.OnBuryNumberChanged();
            }
        }
        private global::System.Nullable<int> _BuryNumber;
        partial void OnBuryNumberChanging(global::System.Nullable<int> value);
        partial void OnBuryNumberChanged();
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMECOM_REFERENCE_THEME", "Theme")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Theme Theme
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMECOM_REFERENCE_THEME", "Theme").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMECOM_REFERENCE_THEME", "Theme").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMECOM_REFERENCE_THEME", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Theme>("IThemeSkyModel.FK_THEMECOM_REFERENCE_THEME", "Theme", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.ThemeDownloadHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// HistoryId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="ThemeDownloadHistory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThemeDownloadHistory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThemeDownloadHistory object.
        /// </summary>
        /// <param name="historyId">Initial value of HistoryId.</param>
        public static ThemeDownloadHistory CreateThemeDownloadHistory(long historyId)
        {
            ThemeDownloadHistory themeDownloadHistory = new ThemeDownloadHistory();
            themeDownloadHistory.HistoryId = historyId;
            return themeDownloadHistory;
        }
        /// <summary>
        /// There are no comments for Property HistoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long HistoryId
        {
            get
            {
                return this._HistoryId;
            }
            set
            {
                this.OnHistoryIdChanging(value);
                this.ReportPropertyChanging("HistoryId");
                this._HistoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HistoryId");
                this.OnHistoryIdChanged();
            }
        }
        private long _HistoryId;
        partial void OnHistoryIdChanging(long value);
        partial void OnHistoryIdChanged();
        /// <summary>
        /// There are no comments for Property AddTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> AddTime
        {
            get
            {
                return this._AddTime;
            }
            set
            {
                this.OnAddTimeChanging(value);
                this.ReportPropertyChanging("AddTime");
                this._AddTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddTime");
                this.OnAddTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _AddTime;
        partial void OnAddTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddTimeChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private global::System.Nullable<int> _UserId;
        partial void OnUserIdChanging(global::System.Nullable<int> value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property UserIp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIp
        {
            get
            {
                return this._UserIp;
            }
            set
            {
                this.OnUserIpChanging(value);
                this.ReportPropertyChanging("UserIp");
                this._UserIp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserIp");
                this.OnUserIpChanged();
            }
        }
        private string _UserIp;
        partial void OnUserIpChanging(string value);
        partial void OnUserIpChanged();
        /// <summary>
        /// There are no comments for Property UserOs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserOs
        {
            get
            {
                return this._UserOs;
            }
            set
            {
                this.OnUserOsChanging(value);
                this.ReportPropertyChanging("UserOs");
                this._UserOs = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserOs");
                this.OnUserOsChanged();
            }
        }
        private string _UserOs;
        partial void OnUserOsChanging(string value);
        partial void OnUserOsChanged();
        /// <summary>
        /// There are no comments for Property UserBrowser in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserBrowser
        {
            get
            {
                return this._UserBrowser;
            }
            set
            {
                this.OnUserBrowserChanging(value);
                this.ReportPropertyChanging("UserBrowser");
                this._UserBrowser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserBrowser");
                this.OnUserBrowserChanged();
            }
        }
        private string _UserBrowser;
        partial void OnUserBrowserChanging(string value);
        partial void OnUserBrowserChanged();
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMEDOW_REFERENCE_THEME", "Theme")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Theme Theme
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMEDOW_REFERENCE_THEME", "Theme").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMEDOW_REFERENCE_THEME", "Theme").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMEDOW_REFERENCE_THEME", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Theme>("IThemeSkyModel.FK_THEMEDOW_REFERENCE_THEME", "Theme", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.ThemeFiles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UrlId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="ThemeFiles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThemeFiles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThemeFiles object.
        /// </summary>
        /// <param name="urlId">Initial value of UrlId.</param>
        public static ThemeFiles CreateThemeFiles(int urlId)
        {
            ThemeFiles themeFiles = new ThemeFiles();
            themeFiles.UrlId = urlId;
            return themeFiles;
        }
        /// <summary>
        /// There are no comments for Property UrlId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UrlId
        {
            get
            {
                return this._UrlId;
            }
            set
            {
                this.OnUrlIdChanging(value);
                this.ReportPropertyChanging("UrlId");
                this._UrlId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UrlId");
                this.OnUrlIdChanged();
            }
        }
        private int _UrlId;
        partial void OnUrlIdChanging(int value);
        partial void OnUrlIdChanged();
        /// <summary>
        /// There are no comments for Property IsDefault in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> IsDefault
        {
            get
            {
                return this._IsDefault;
            }
            set
            {
                this.OnIsDefaultChanging(value);
                this.ReportPropertyChanging("IsDefault");
                this._IsDefault = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsDefault");
                this.OnIsDefaultChanged();
            }
        }
        private global::System.Nullable<short> _IsDefault;
        partial void OnIsDefaultChanging(global::System.Nullable<short> value);
        partial void OnIsDefaultChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this.ReportPropertyChanging("Url");
                this._Url = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Url");
                this.OnUrlChanged();
            }
        }
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property Source in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this.OnSourceChanging(value);
                this.ReportPropertyChanging("Source");
                this._Source = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Source");
                this.OnSourceChanged();
            }
        }
        private global::System.Nullable<short> _Source;
        partial void OnSourceChanging(global::System.Nullable<short> value);
        partial void OnSourceChanged();
        /// <summary>
        /// There are no comments for Property AddTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> AddTime
        {
            get
            {
                return this._AddTime;
            }
            set
            {
                this.OnAddTimeChanging(value);
                this.ReportPropertyChanging("AddTime");
                this._AddTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddTime");
                this.OnAddTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _AddTime;
        partial void OnAddTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddTimeChanged();
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMEFIL_REFERENCE_THEME", "Theme")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Theme Theme
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMEFIL_REFERENCE_THEME", "Theme").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMEFIL_REFERENCE_THEME", "Theme").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMEFIL_REFERENCE_THEME", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Theme>("IThemeSkyModel.FK_THEMEFIL_REFERENCE_THEME", "Theme", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.ThemeTag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="ThemeTag")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThemeTag : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThemeTag object.
        /// </summary>
        /// <param name="tagId">Initial value of TagId.</param>
        public static ThemeTag CreateThemeTag(int tagId)
        {
            ThemeTag themeTag = new ThemeTag();
            themeTag.TagId = tagId;
            return themeTag;
        }
        /// <summary>
        /// There are no comments for Property TagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TagId
        {
            get
            {
                return this._TagId;
            }
            set
            {
                this.OnTagIdChanging(value);
                this.ReportPropertyChanging("TagId");
                this._TagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagId");
                this.OnTagIdChanged();
            }
        }
        private int _TagId;
        partial void OnTagIdChanging(int value);
        partial void OnTagIdChanged();
        /// <summary>
        /// There are no comments for Property TagName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName
        {
            get
            {
                return this._TagName;
            }
            set
            {
                this.OnTagNameChanging(value);
                this.ReportPropertyChanging("TagName");
                this._TagName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TagName");
                this.OnTagNameChanged();
            }
        }
        private string _TagName;
        partial void OnTagNameChanging(string value);
        partial void OnTagNameChanged();
        /// <summary>
        /// There are no comments for Property TagIcon in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TagIcon
        {
            get
            {
                return this._TagIcon;
            }
            set
            {
                this.OnTagIconChanging(value);
                this.ReportPropertyChanging("TagIcon");
                this._TagIcon = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TagIcon");
                this.OnTagIconChanged();
            }
        }
        private string _TagIcon;
        partial void OnTagIconChanging(string value);
        partial void OnTagIconChanged();
        /// <summary>
        /// There are no comments for Property TagDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TagDescription
        {
            get
            {
                return this._TagDescription;
            }
            set
            {
                this.OnTagDescriptionChanging(value);
                this.ReportPropertyChanging("TagDescription");
                this._TagDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TagDescription");
                this.OnTagDescriptionChanged();
            }
        }
        private string _TagDescription;
        partial void OnTagDescriptionChanging(string value);
        partial void OnTagDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsSystem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> IsSystem
        {
            get
            {
                return this._IsSystem;
            }
            set
            {
                this.OnIsSystemChanging(value);
                this.ReportPropertyChanging("IsSystem");
                this._IsSystem = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsSystem");
                this.OnIsSystemChanged();
            }
        }
        private global::System.Nullable<short> _IsSystem;
        partial void OnIsSystemChanging(global::System.Nullable<short> value);
        partial void OnIsSystemChanged();
        /// <summary>
        /// There are no comments for Property AddTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> AddTime
        {
            get
            {
                return this._AddTime;
            }
            set
            {
                this.OnAddTimeChanging(value);
                this.ReportPropertyChanging("AddTime");
                this._AddTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddTime");
                this.OnAddTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _AddTime;
        partial void OnAddTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddTimeChanged();
        /// <summary>
        /// There are no comments for ThemeTagMap in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTagMap")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ThemeTagMap> ThemeTagMap
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ThemeTagMap>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTagMap");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ThemeTagMap>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTagMap", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for IThemeSkyModel.ThemeTagMap in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ThemeId
    /// TagId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="IThemeSkyModel", Name="ThemeTagMap")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ThemeTagMap : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ThemeTagMap object.
        /// </summary>
        /// <param name="themeId">Initial value of ThemeId.</param>
        /// <param name="tagId">Initial value of TagId.</param>
        public static ThemeTagMap CreateThemeTagMap(int themeId, int tagId)
        {
            ThemeTagMap themeTagMap = new ThemeTagMap();
            themeTagMap.ThemeId = themeId;
            themeTagMap.TagId = tagId;
            return themeTagMap;
        }
        /// <summary>
        /// There are no comments for Property ThemeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ThemeId
        {
            get
            {
                return this._ThemeId;
            }
            set
            {
                this.OnThemeIdChanging(value);
                this.ReportPropertyChanging("ThemeId");
                this._ThemeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ThemeId");
                this.OnThemeIdChanged();
            }
        }
        private int _ThemeId;
        partial void OnThemeIdChanging(int value);
        partial void OnThemeIdChanged();
        /// <summary>
        /// There are no comments for Property TagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TagId
        {
            get
            {
                return this._TagId;
            }
            set
            {
                this.OnTagIdChanging(value);
                this.ReportPropertyChanging("TagId");
                this._TagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagId");
                this.OnTagIdChanged();
            }
        }
        private int _TagId;
        partial void OnTagIdChanging(int value);
        partial void OnTagIdChanged();
        /// <summary>
        /// There are no comments for Property SortNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortNumber
        {
            get
            {
                return this._SortNumber;
            }
            set
            {
                this.OnSortNumberChanging(value);
                this.ReportPropertyChanging("SortNumber");
                this._SortNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortNumber");
                this.OnSortNumberChanged();
            }
        }
        private global::System.Nullable<int> _SortNumber;
        partial void OnSortNumberChanging(global::System.Nullable<int> value);
        partial void OnSortNumberChanged();
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMETAG_REFERENCE_THEME", "Theme")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Theme Theme
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEME", "Theme").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEME", "Theme").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Theme in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Theme>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEME", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Theme>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEME", "Theme", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ThemeTag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("IThemeSkyModel", "FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ThemeTag ThemeTag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ThemeTag>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTag").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ThemeTag>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTag").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ThemeTag in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ThemeTag> ThemeTagReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ThemeTag>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ThemeTag>("IThemeSkyModel.FK_THEMETAG_REFERENCE_THEMETAG", "ThemeTag", value);
                }
            }
        }
    }
}
